# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 20 * * 0'

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
/*Cambiar el color de fondo a naranja*/
body {
   background-color: #FFA500;
}

/*Cambiar el color de los enlaces*/
a {
   color: #FFA500;
}

/*Cambiar el color del botón*/
.button {
   background-color: #FFA500;
   color: #FFFFFF;
}

/*Curvar los bordes de los botones*/
.button {
   border-radius: 20px;
}

/*Curvar los bordes de las imágenes*/
img {
   border-radius: 10px;
}
<strong>Estudis.deptsocio</strong>
